### ISSUE TITLE
REST API Select

### ISSUE THREAD

**Issue by elvishp2006** [htmlburger/awesome-carbon-fields#2]
Hi, can you add this field on this list? https://github.com/elvishp2006/carbon-field-rest-api-select

**Comment by vvasilev-** [comment]
Hi @elvishp2006,

Thank you for your contribution! Could you open a PR to add this one?

**Comment by vvasilev-** [comment]
Closed by PR https://github.com/htmlburger/awesome-carbon-fields/pull/3.
